name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: ./.github/actions/setup-nix

      - name: Install dependencies
        run: nix develop -c make deps

      - name: Run frontend checks
        run: nix develop -c make check
