name: CI/CD Deployment to Cloud Run

on:
  push:
    branches:
      - '**' # Trigger on any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/143436458586/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-sa@japan-visa-predictions.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: japan-visa-predictions

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y docker.io sops

      - name: Export SOPS Private Key
        run: echo "${{ secrets.CI_AGE_KEY }}" > ~/.age-key

      - name: Deploy to Cloud Run
        env:
          SOPS_AGE_KEY_FILE: ~/.age-key
        run: make deploy
