name: CI/CD Deployment to Cloud Run

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: japan-visa-predictions

      - name: Set up Docker
        uses: docker/setup-docker-action@v2

      - name: Install sops
        uses: nhedger/setup-sops@v2
        with:
          version: 'latest'

      - name: Create SOPS Keys
        run: |
          mkdir -p ~/.sops
          echo "${{ secrets.CI_AGE_KEY }}" > ~/.sops/keys.txt
          chmod 600 ~/.sops/keys.txt
        env:
          SOPS_AGE_KEY_FILE: ~/.sops/keys.txt

      - name: Validate SOPS Key
        run: |
          if [ ! -f ~/.sops/keys.txt ]; then
            echo "Error: SOPS keys file not found"
            exit 1
          fi
          echo "SOPS keys file exists and is valid"

      - name: Test SOPS Decryption
        env:
          SOPS_AGE_KEY_FILE: ~/.sops/keys.txt
        run: |
          sops -d secrets/.env.enc > /tmp/.env
          cat /tmp/.env

      - name: Deploy to Cloud Run
        env:
          SOPS_AGE_KEY_FILE: ~/.sops/keys.txt
        run: make deploy
